edition = "2018"

max_width = 100
use_small_heuristics = "Max"

newline_style = "Unix"

use_field_init_shorthand = true
use_try_shorthand = true

# I'd like to order these by specificity.
reorder_imports = false
reorder_modules = false
