My personal config files. Clone and create appropriate symbolic links.

* .autokey
- Install
- Add .autokey dir via GUI
- Make it auto-start
- Monkey-patch =/usr/lib/python2.7/dist-packages/autokey/model.py= to make autokey use regular expressions to exclude windows, not including.
#+begin_src python
class AbstractWindowFilter:
    ...

    def _should_trigger_window_title(self, windowInfo):
        r = self.get_applicable_regex()
        if r is not None:
            return not (r.match(windowInfo[0]) or r.match(windowInfo[1]))
        else:
            return True
#+end_src


* Konsole
Symlink =~/.kde/share/apps/konsole= to =konsole=
Symlink =~/.kde/share/config/konsolerc= to =konsolerc=

* Gnome-terminal
Just in case (use Konsole if possible).
Symlink =~/.gconf/apps/gnome-terminal= to =gnome-terminal=

* Redshift
Symlink =~/.conf/redshift.conf= to =redshift.conf=

* IntelliJ
#+begin_src sh
ln -s ~/dotfiles/IntelliJ/keymap.xml ~/Library/Preferences/IdeaIC2017.2/keymaps/ubolonton.xml
ln -s ~/dotfiles/IntelliJ/keymap.xml ~/Library/Preferences/Gogland1.0/keymaps/ubolonton.xml
#+end_src


* Karabiner
Symlink =~/Users/ubolonton/Library/Application Support/Karabiner= to =Karabiner=

* Karabiner-Elements
#+begin_src shell
ln -s ../dotfiles/Karabiner-Elements ~/.config/karabiner
#+end_src

* iTerm2
Look for ~Load preferences from a custom folder or URL~, set the directory to =dotfiles/iTerm2=.

* Firefox
Symlink ~<profile>/chrome/userChrome.css~ [[file:Firefox/userChrome.css][to userChrome.css]]
Paste content of [[file:Firefox/tree-style-tab-extra-rules.css]] into the custom css box.
