My personal config files. Clone and create appropriate symbolic links.

#+begin_src shell
stow -v zsh git tmux
#+end_src


* .autokey
- Install
- Add .autokey dir via GUI
- Make it auto-start
- Monkey-patch =/usr/lib/python2.7/dist-packages/autokey/model.py= to make autokey use regular expressions to exclude windows, not including.
#+begin_src python
class AbstractWindowFilter:
    ...

    def _should_trigger_window_title(self, windowInfo):
        r = self.get_applicable_regex()
        if r is not None:
            return not (r.match(windowInfo[0]) or r.match(windowInfo[1]))
        else:
            return True
#+end_src

* Konsole
Symlink =~/.kde/share/apps/konsole= to =konsole=
Symlink =~/.kde/share/config/konsolerc= to =konsolerc=

* Gnome-terminal
Just in case (use Konsole if possible).
Symlink =~/.gconf/apps/gnome-terminal= to =gnome-terminal=

* iTerm2
Look for ~Load preferences from a custom folder or URL~, set the directory to =dotfiles/iTerm2=.

* Firefox
- Go to about:config, set ~toolkit.legacyUserProfileCustomizations.stylesheets~ to ~true~.
  - Go to about:profile to find the profile setting location.
  - Symlink ~<profile>/chrome/userChrome.css~ [[file:Firefox/userChrome.css][to userChrome.css]]
- Paste content of [[file:Firefox/tree-style-tab-extra-rules.css]] into the custom css box.

* OS X
#+begin_src shell
ln -s dotfiles/.config ~/
ln -s dotfiles/.oh-my-zsh ~/
ln -s dotfiles/.inputrc ~/
ln -s dotfiles/.jshint.json ~/
ln -s dotfiles/.lein ~/
ln -s dotfiles/.psqlrc ~/
ln -s dotfiles/.tmux.conf ~/
ln -s dotfiles/.rustfmt.toml ~/
ln -s dotfiles/.clickhouse-client ~/
ln -s dotfiles/.duckdbrc ~/
ln -s dotfiles/.digrc ~/

tic ~/dotfiles/xterm-256color-italic.terminfo

export INTELLIJ_CONF_DIR=~/Library/'Application Support'/JetBrains/IntelliJIdea2023.1
ln -f -s ~/dotfiles/IntelliJ/keymaps/* $INTELLIJ_CONF_DIR/keymaps/
ln -f -s ~/dotfiles/IntelliJ/options/* $INTELLIJ_CONF_DIR/options/
ln -f -s ~/dotfiles/IntelliJ/tools/* $INTELLIJ_CONF_DIR/tools/
ln -f -s ~/dotfiles/IntelliJ/codestyles/* $INTELLIJ_CONF_DIR/codestyles/

ln -s "$HOME"/dotfiles/.config/Code ~/Library/'Application Support'/
#+end_src
