My personal config files. Clone and create appropriate symbolic links.

* .autokey
- Install
- Add .autokey dir via GUI
- Make it auto-start
- Monkey-patch =/usr/lib/python2.7/dist-packages/autokey/model.py= to make autokey use regular expressions to exclude windows, not including.
#+begin_src python
class AbstractWindowFilter:
    ...

    def _should_trigger_window_title(self, windowInfo):
        r = self.get_applicable_regex()
        if r is not None:
            return not (r.match(windowInfo[0]) or r.match(windowInfo[1]))
        else:
            return True
#+end_src


* Konsole
Symlink =~/.kde/share/apps/konsole= to =konsole=
Symlink =~/.kde/share/config/konsolerc= to =konsolerc=

* Gnome-terminal
Just in case (use Konsole if possible).
Symlink =~/.gconf/apps/gnome-terminal= to =gnome-terminal=

* Redshift
Symlink =~/.conf/redshift.conf= to =redshift.conf=

* Karabiner
Symlink =~/Users/ubolonton/Library/Application Support/Karabiner= to =Karabiner=

* iTerm2
Look for ~Load preferences from a custom folder or URL~, set the directory to =dotfiles/iTerm2=.

* Firefox
Symlink ~<profile>/chrome/userChrome.css~ [[file:Firefox/userChrome.css][to userChrome.css]]
Paste content of [[file:Firefox/tree-style-tab-extra-rules.css]] into the custom css box.

* OS X
#+begin_src shell
  ln -s dotfiles/.z* ~/
  ln -s dotfiles/.oh-my-zsh ~/
  ln -s dotfiles/.gitconfig ~/
  ln -s dotfiles/.gitattributes ~/
  ln -s dotfiles/.gitignore_global ~/
  ln -s dotfiles/.inputrc ~/
  ln -s dotfiles/.jshint.json ~/
  ln -s dotfiles/.lein ~/
  ln -s dotfiles/.psqlrc ~/
  ln -s dotfiles/.tmux.conf ~/
  ln -s dotfiles/.rustfmt.toml ~/

tic ~/dotfiles/xterm-256color-italic.terminfo

  ln -s ../dotfiles/Karabiner-Elements ~/.config/karabiner

  ln -s ~/dotfiles/IntelliJ/keymaps/* ~/Library/Preferences/PyCharmCE2018.2/keymaps/

  export INTELLIJ_CONF_DIR=~/Library/ApplicationSupport/JetBrains/IntelliJIdea2021.1
  ln -s ~/dotfiles/IntelliJ/keymaps/* $INTELLIJ_CONF_DIR/keymaps/
  ln -s ~/dotfiles/IntelliJ/options/* $INTELLIJ_CONF_DIR/options/
  ln -s ~/dotfiles/IntelliJ/tools/* $INTELLIJ_CONF_DIR/tools/

  mkdir -p ~/Library/'Application Support'/Code/User/
  cd ~/Library/'Application Support'/Code/User/
  ln -s ../../../../dotfiles/'Visual Studio Code'/* ./
#+end_src
