foreground #cfd2d0
background #26292c
# background_opacity 0.5

black
color0 #000000
red
color1 #d77b79
green
color2 #c1c67a
yellow
color3 #f3cf86
blue
color4 #92b1c9
magenta
color5 #c0a6c7
cyan
color6 #9ac8c3
white
color7 #fffefe
