foreground #cfd2d0
background #26292c
# background_opacity 0.5

# TODO: Different colors for 8-15

# https://gemini.google.com/app/3a0aab188aa8d239
#
# Between 1.89 and 1.93, Cargo's coloring crate (anstream) was updated to prioritize Theme
# Consistency over Fixed Palettes.

# black
color0 #000000
color8 #000000

# red
color1 #d77b79
color9 #d77b79

# green
color2 #c1c67a
color10 #c1c67a

# yellow
color3 #f3cf86
color11 #f3cf86

# blue
color4 #92b1c9
color12 #92b1c9

# magenta
color5 #c0a6c7
color13 #c0a6c7

# cyan
color6 #9ac8c3
color14 #9ac8c3

# white
color7 #fffefe
color15 #fffefe
