format = """\
$username\
$hostname\
$rust\
$package\
$dotnet\
$golang\
$java\
$nodejs\
$python\
$ruby\
$nix_shell\
$directory\
$cmd_duration\
$time\
$line_break\
$character\
"""

[username]
style_user = "bold green"
show_always = true

[hostname]
style = "bold red"
ssh_only = false

[character]
use_symbol_for_status = true
success_symbol = "😃"
error_symbol = "😱"
# success_symbol = "➜"
# error_symbol = "✗"

[directory]
truncation_length = 8
fish_style_pwd_dir_length = 2
truncate_to_repo = false
style = "bold blue"

[time]
disabled = false
time_format = "%a %Y-%m-%d %H:%M:%S %z"
style = "cyan"

[rust]
style = "dimmed"

[nodejs]
style = "dimmed"

[python]
style = "dimmed"

[package]
style = "dimmed"

[kubernetes]
disabled = false