#! /bin/sh

# HACK to use firefox's xulrunner instead of using another xulrunner.
# Can't understand why don't they just distribute xulrunner.

exec firefox --app /home/ubolonton/Programming/Tools/conkeror/application.ini "$@"
