[settings]
# `mise` doesn't support lockfile for global tools. Or at least that's what Gemini said. We work
# around by via the ~/dotfiles project.
lockfile = true
experimental = true
status.show_env = true
npm.package_manager = "bun"
pipx.uvx = true

[tools]
# Things that better come from the system package manager:
#
# So that `cargo:` tools can use it for compiling.
# sccache =
#
# Could be useful system-wide.
# rg =
# exa =

# Things that should be project-specific.
# bindgen =

# General
fd = "latest"
bat = "latest"
"cargo:mdcat" = "latest"
"cargo:bingrep" = "latest"

# REPLs
babashka = { version = "latest", exe = "bb" }
clickhouse = "26"
duckdb = "1"

# Project management: build tools, task runners
scie-pants = "latest"
just = "1"
mdbook = "latest"

# Language-specific dev tools
pdm = "2"
zig = "latest"
"cargo:cargo-outdated" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-zigbuild" = "latest"
"cargo:cargo-watch" = "latest"

# Unsorted
hyperfine = "latest"
tokei = "latest"
starship = "latest"
"pipx:tmuxp" = "latest"
"pipx:magic-wormhole" = "latest"
stern = "latest"
